modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved unless otherwise explicitly stated." # SWEM is All rights reserved and due to this mod being heavily tied to their code, this mod is also listed as All Rights reservered...
#HOWEVER -- I am open for branches and collaboration on my mod that respects SWEM's rights. Reach out to me and we can discuss your plans and ideas!

issueTrackerURL="https://github.com/FloweringTre/Tre-Tack-Shop/issues"

[[mods]]

modId="tretackshop"
version="${file.jarVersion}"
displayName="Tre's Tack Shop"

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display

logoFile="logo.png"
credits="The SWEM Team for use of their models/entities/classes"
authors="kyraltre"


description='''An addon mod to SWEM that expands the number of tack items in the game for the community to use to add new textures to the game without overriding the original tack items. It also includes ribbons and trophy models from the original SWEM mod in order to produce ribbons and trophies that can be displayed as the creators intended them to be but now in an item frame instead of a placeable block, thus keeping the name/NBT data of the item.

**All items only be obtainable in the creative menu / give commands, there are no recipes in this mod.**
Basically, a little add-on mod that acts like a custom tack shop for players and servers to use to gain custom tack based on their resource packs.

Also include new models of my own design as I make them.

Please see the link below for our discord for updates, questions, and a how-to guide for making resource packs for this mod.
https://discord.gg/GuYRWK22Mx'''


# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tretackshop]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.tretackshop]] #our parent mod
    modId="swem"
    mandatory=false
    versionRange="[1.3.0-15,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tretackshop]] #parent mod dependancies
    modId = "geckolib3"
    mandatory = false
    versionRange = "[3.0.57,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.tretackshop]] #parent mod dependancies
    modId = "playeranimator"
    mandatory = false
    versionRange = "[0.4.0+1.18,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.tretackshop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
