modLoader="javafml"
loaderVersion="[40,)"
license="MIT" # SWEM is All rights reserved - Do not overstep this.
#Tre's Tack Shop welcomes others help and use to make it better for the community use though <3

issueTrackerURL="https://github.com/FloweringTre/Tre-Tack-Shop/issues"

[[mods]]

modId="tretackshop"
version="${file.jarVersion}"
displayName="Tre's Tack Shop"

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display

logoFile="logo.png"
credits="The SWEM Team for use of their models/entities/classes"
authors="kyraltre"


description=''' This mod adds new tack and prize items from SWEM for resource pack uses.

 Some new models are added of my own design but most items in this pack are just adding new versions of the original SWEM items.

 Please see the link below for our discord for updates, questions, and a how-to guide for making resource packs for this mod.
 https://discord.gg/GuYRWK22Mx'''


# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tretackshop]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.tretackshop]] #our parent mod
    modId="swem"
    mandatory=false
    versionRange="[1.3.0-15,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tretackshop]] #parent mod dependancies
    modId = "geckolib3"
    mandatory = false
    versionRange = "[3.0.57,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.tretackshop]] #parent mod dependancies
    modId = "playeranimator"
    mandatory = false
    versionRange = "[0.4.0+1.18,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.tretackshop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
